include ../defaults.mk

NAME		= twolame
VERSION		= 0.4.0

HOMEPAGE	= https://www.twolame.org/
DESCRIPTION	= MPEG Audio Layer 2 (MP2) encoder
DOWNLOAD = https://sourceforge.net/projects/${NAME}/files/${NAME}/$(VERSION)/

CONFIGURE_ARGS += --disable-sndfile --without-gnu-ld

include ../port.mk
