include ../defaults.mk

NAME		= git
VERSION		= 2.22.0

DESCRIPTION	= source code management
HOMEPAGE	= https://git-scm.com/downloads
DOWNLOAD	= https://mirrors.edge.kernel.org/pub/software/scm/git/

CONFIGURE_ARGS +=			\
		--without-expat		\
		--without-iconv		\
		--without-tcltk

include ../port.mk
