NAME		= pstree
VERSION		= 2.39

DESCRIPTION	= list processes as a tree
HOMEPAGE	= http://www.thp.uni-duisburg.de/pstree/
DOWNLOAD	= ftp://ftp.thp.uni-duisburg.de/pub/source/

SRCDIR		= work
CONFIGURE	=

include ../ports.mk
