include ../defaults.mk

NAME		= pstree
VERSION		= 2.40

DESCRIPTION	= list processes as a tree
DOWNLOAD	= https://github.com/FredHucht/pstree/archive/refs/tags/
DISTNAME	= v$(VERSION).$(SUFFIX)

CONFIGURE	=

include ../port.mk
