include ../defaults.mk

NAME		= bzip2
VERSION		= 1.0.6

DESCRIPTION	= compression library and tools
HOMEPAGE	= https://web.archive.org/web/20180624184806/http://www.bzip.org
DOWNLOAD	= $(HOMEPAGE)/$(VERSION)
CONFIGURE	= 

include ../port.mk
