include ../defaults.mk

NAME		= automake
VERSION		= 1.16

DESCRIPTION	= create Makefiles for GNU software
HOMEPAGE	= https://www.gnu.org/software/automake/
DOWNLOAD	= http://ftp.gnu.org/gnu/automake/

include ../port.mk
