include ../defaults.mk

NAME		= mandoc
VERSION		= 1.14.4

DESCRIPTION	= UNIX manpage compiler
HOMEPAGE	= https://mandoc.bsd.lv/
DOWNLOAD	= $(HOMEPAGE)/snapshots/

CONFIGURE_ARGS	=

include ../port.mk
