NAME		= mandoc
VERSION		= 1.14.4

DESCRIPTION	= UNIX manpage compiler
HOMEPAGE	= https://mandoc.bsd.lv/
DOWNLOAD	= https://mandoc.bsd.lv/snapshots/

CONFIGURE_ARGS	=
FAKEDIR		= /tmp/fakemandoc

include ../ports.mk
