include ../defaults.mk

NAME		= libunistring
VERSION		= 1.0

DESCRIPTION	= manipulate unicode strings
HOMEPAGE	= https://www.gnu.org/software/libunistring/
DOWNLOAD	= https://ftp.gnu.org/gnu/$(NAME)/

include ../port.mk
