include ../defaults.mk

NAME		= ftp
VERSION		= 1.0.1

DESCRIPTION	= Internet file transfer program
HOMEPAGE	= https://github.com/janstary/ftp/
DOWNLOAD	= $(HOMEPAGE)/releases/download/$(VERSION)/

#DEPS		= libressl
CONFIGURE_ARGS	=

include ../port.mk
