include ../defaults.mk

NAME		= libopusenc
VERSION		= 0.2

DESCRIPTION	= encode Opus files and streams
HOMEPAGE	= http://www.opus-codec.org
DOWNLOAD	= https://archive.mozilla.org/pub/opus

include ../port.mk
