include ../defaults.mk

NAME		= libtool
VERSION		= 2.4

DESCRIPTION	= library support script
HOMEPAGE	= https://www.gnu.org/software/libtool/
DOWNLOAD	= http://ftp.gnu.org/gnu/libtool/

include ../port.mk
