include ../defaults.mk

NAME		= libsamplerate
VERSION		= 0.1.9

DESCRIPTION	= sample rate converter
HOMEPAGE	= http://www.mega-nerd.com/SRC/
DOWNLOAD	= $(HOMEPAGE)

CONFIGURE_ARGS +=			\
		--disable-fftw		\
		--disable-cpu-clip	\
		--disable-sndfile

include ../port.mk
