include ../defaults.mk

NAME		= pkg-config
VERSION		= 0.29.2

DESCRIPTION	= manage compiler flags for libraries
HOMEPAGE	= http://pkg-config.freedesktop.org/
DOWNLOAD	= $(HOMEPAGE)/releases

CONFIGURE_ARGS	+=			\
		--with-internal-glib	\
		--without-gcov

include ../port.mk
