include ../defaults.mk

NAME		= autoconf
VERSION		= 2.69

DESCRIPTION	= configure GNU software
HOMEPAGE	= https://www.gnu.org/software/autoconf/
DOWNLOAD	= http://ftp.gnu.org/gnu/autoconf/

include ../port.mk
