include ../defaults.mk

NAME		= vo-amrwbenc
VERSION		= 0.1.3

DESCRIPTION	= Adaptive Multi Rate speech codec
HOMEPAGE	= https://sourceforge.net/projects/opencore-amr/
DOWNLOAD	= ${HOMEPAGE}/files/${NAME}/

CONFIGURE_ARGS += --enable-example


include ../port.mk
