NAME		= libvorbis
VERSION		= 1.3.6

DESCRIPTION	= the Ogg Vorbis audio codec
HOMEPAGE	= https://xiph.org/vorbis/
DOWNLOAD	= https://ftp.osuosl.org/pub/xiph/releases/vorbis/

#depends_build   port:pkgconfig
#depends_lib     port:libogg

#patchfiles          patch-docdir.diff

include ../ports.mk
