include ../defaults.mk

NAME		= libvorbis
VERSION		= 1.3.7

DESCRIPTION	= the Ogg Vorbis audio codec
HOMEPAGE	= https://xiph.org/vorbis/
DOWNLOAD	= https://ftp.osuosl.org/pub/xiph/releases/vorbis/

include ../port.mk
