NAME		= libevent
VERSION		= 2.1.8-stable

DESCRIPTION	= event notification library
HOMEPAGE	= http://libevent.org
GITHUB		= https://github.com/$(NAME)/$(NAME)
DOWNLOAD	= $(GITHUB)/releases/download/release-$(VERSION)

#depends_lib         path:lib/libssl.dylib:openssl
#patchfiles          patch-libressl.diff
#patch.pre_args      -p1
#use_autoreconf      yes
#test.run            yes
#test.target         verify

include ../ports.mk
