include ../defaults.mk

NAME		= python
VERSION		= 3.10.4

DESCRIPTION	= the Python programming language
HOMEPAGE	= https://www.python.org
DOWNLOAD	= $(HOMEPAGE)/ftp/python/$(VERSION)
DISTNAME	= Python-$(VERSION).tgz

include ../port.mk
