include ../defaults.mk

NAME		= libressl
VERSION		= 3.5.2

DESCRIPTION	= tls/crypto stack
HOMEPAGE	= https://www.libressl.org
DOWNLOAD	= https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

include ../port.mk
