include ../defaults.mk

NAME		= libiconv
VERSION		= 1.16

DESCRIPTION	= character set conversion
HOMEPAGE	= https://www.gnu.org/software/libiconv/
DOWNLOAD	= https://ftp.gnu.org/pub/gnu/libiconv/

include ../port.mk
