include ../defaults.mk

NAME		= opusfile
VERSION		= 0.12
DESCRIPTION	= decode opus files

HOMEPAGE	= http://www.opus-codec.org
DOWNLOAD	= https://downloads.xiph.org/releases/opus/

include ../port.mk
