NAME		= opusfile
VERSION		= 0.10
DESCRIPTION	= decode opus files

HOMEPAGE	= http://www.opus-codec.org
DOWNLOAD	= https://archive.mozilla.org/pub/opus

#env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ pkg-config --libs opus
#depends_lib         path:lib/libssl.dylib:openssl \
                    #port:libogg \
                    #port:libopus

#patchfiles          patch-libressl.diff

include ../ports.mk
